### ISSUE TITLE
 如何使用

### ISSUE THREAD

**Issue by zounick** [psygame/hack_ssjj#1]
请问开发者 这要如何使用呢  

我做过跟这类似的东西 不过那是有指定加载文件夹的

**Comment by psygame** [comment]
通过dnSpy修改源代码的dll，使其加载该项目生成的dll文件，以达到Hack的目的。

**Comment by zounick** [comment]
> [dspy] dll，[dll]，[哈克]

感谢

**Comment by psygame** [comment]
> > 通过dnSpy修改源代码的dll，使其加载该项目生成的dll文件，以达到Hack的目的。
> 
> 感谢

上传的Assembly-CSharp.dll 文件已经包含了加载dll的代码逻辑。搜HackManager。

**Comment by psygame** [comment]
入群吧~ [https://jq.qq.com/?_wv=1027&k=9SwVcKWF](https://jq.qq.com/?_wv=1027&k=9SwVcKWF)
